#+TITLE: Reparameterizing Bayesian state-space models for more reliable fits

Bayesian state space models have played an important role in fisheries for many years. These models are typically fit using Markov chain Monte Carlo, often using general-purpose software such as BUGS, JAGS, and more recently Stan. Stan uses a sampler that takes advantage of gradient information to make proposals based on the solution of a system of ordinary differential equations. This typically results in less dependence between iterations. Areas of high curvature generate "divergences," which serve as useful diagnostics, indicating areas of the parameter space that cannot be adequately explored. Not exploring the entire parameter space can result in biased inferences. Previous work has shown that the most reliable way of eliminating these divergences is to reparameterize the model in a way that eliminates areas of high curvature. Here I explore reparameterizations of the Schaefer biomass dynamics model and consequences for model fit diagnostics.
